name: Check
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-environment

      - name: Check e2k-rs
        working-directory: crates/e2k-rs
        run: |
          task generate_models
          cargo clippy --all-targets --all-features -- -D warnings
          cargo fmt --all -- --check

      - name: Check e2k-js
        working-directory: crates/e2k-js
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
          cargo fmt --all -- --check
          cd js
          pnpm run lint
          pnpm run typecheck
          pnpm run test
