# 学習に使うデータ。
train_data: ./vendor/data.jsonl
# 評価に使うデータ。
eval_data: ./vendor/unidic_words.jsonl
# 評価用データのうち、学習中に評価に使う単語の数。（eval.pyでは全てのデータを使います）
# nullの場合は全てのデータを使います。
eval_max_words: 100
# モデルの次元数。
dim: 256
# 学習するエポック数。
max_epochs: 10
# 最新のエポックから保存するモデルの数。
num_last_models_to_keep: 2
# 保存する上位のモデルの数。
num_best_models_to_keep: 2
# 乱数のシード。
seed: 0
# Optimizerの学習率
optimizer_lr: 0.001
